//local host
http://localhost:8080/tasks
################################################
//render
# GET https://project2-am.onrender.com

###################################################
###CREATE NEW TASK
POST http://localhost:8080/tasks HTTP/1.1
Content-Type: application/json

{
    "activity": "Put gas in the car",
    "duration": "30 minutes",
    "date": "10/12/2022",
    "time": "09:00",
    "place": "costco",
    "description": "fill up the tank and get a new air filter",
  "priority": "high"
}

#  POST https://project2-am.onrender.com/tasks HTTP/1.1
# Content-Type: application/json
###################################################
## UPDATE TASK

PUT http://localhost:8080/tasks/6345f1f9a0e046f19ab46382 HTTP/1.1
Content-Type: application/json

{
    "activity": "Deposit cash into the bank",
    "duration": "30 minutes",
    "date": "10/19/2022",
    "time": "14:00",
    "place": "bank of america",
    "description": "Deposit the cash for the money I borrowed from my friend",
  "priority": "high"
}

##############################################################################
# DELETE TASK
DELETE http://localhost:8080/tasks/6345f1f9a0e046f19ab46382 HTTP/1.1
