//local host
http://localhost:8080/tasks
################################################
//render
# GET https://project2-am.onrender.com

###################################################
###CREATE NEW TASK
POST http://localhost:8080/tasks HTTP/1.1
Content-Type: application/json
  
  {
    "activity": "plant a tree",
        "duration": "2 hours",
        "date": "10/10/2020",
        "time": "09:00",
        "place": "rexburg park",
        "description": "Plant a tree to get more oxigen",
        "priority": "low",
  }


###################################################
#  POST https://project2-am.onrender.com/tasks HTTP/1.1
# Content-Type: application/json
###################################################
## UPDATE TASK

PUT http://localhost:8080/tasks/635b5c95ae81ea4d5f548435 HTTP/1.1
Content-Type: application/json

{
  "activity": "get pizza",
  "duration": "1 hour",
  "date": "10/20/2022",
  "time": "10:00",
  "place": "Walmart",
  "description": "go get pizza with the dudes",
  "priority": "low",
  "completed": "true"
}

##############################################################################
# DELETE TASK
DELETE http://localhost:8080/tasks/6345f423a0e046f19ab46385 HTTP/1.1
