//local host
http://localhost:8080/tasks
################################################
//render
# GET https://project2-am.onrender.com

###################################################
###CREATE NEW TASK
POST http://localhost:8080/tasks HTTP/1.1
Content-Type: application/json
  
  {
  "activity": "plant a tree",
  "duration": "1 hour",
  "date": "10/10/2020",
  "time": "09:00",
  "place": "Rexburg Downtown",
  "description": "Walk the dog around the block",
  "priority": "medium"
}


###################################################
#  POST https://project2-am.onrender.com/tasks HTTP/1.1
# Content-Type: application/json
###################################################
## UPDATE TASK

PUT http://localhost:8080/tasks/6345f423a0e046f19ab46385 HTTP/1.1
Content-Type: application/json

{
  "activity": "Go party",
  "duration": "3 hours",
  "date": "10/12/2022",
  "time": "09:00",
  "place": "Rexburg Downtown",
  "description": "go party with friends on the weekend",
  "priority": "medium"
}

##############################################################################
# DELETE TASK
DELETE http://localhost:8080/tasks/6345f423a0e046f19ab46385 HTTP/1.1
